import pgym1 from "../../Assets/Partnerimg/pgym1.png";

export const partnersData = [
  {
    doctor: [
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "DOCTOR",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
    ],
    gym: [
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",

        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "Gym",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
    ],
    fitnesscoach: [
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",

        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
      {
        partnerName: "fitnesscoach",
        partnerProfile: pgym1,
        partnerAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
        partnerPhone: "9999-999-999",
        partnerEmail: "partner@posh.com",
      },
    ],
  },

  // doctors={},
  // fitnessCoaches={}
];
